---
# for CentOS 7 nginx setting
    - name: Install remi
      yum: name='http://rpms.famillecollet.com/enterprise/remi-release-7.rpm' state=present
      when:
          - USE_LOCAL_REPO is not defined
 
    - name: setup Nginx repo
      template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo
    
    - name: Install Nginx and Vsftp
      yum: name={{ item }} state=present
      with_flattened:
        - nginx
        - vsftpd
       
    - name: Install PHP from remi repo
      yum: name={{ item }} enablerepo={{ PHP_VERSION }} state=present
      with_flattened:
        - php-mcrypt
        - php-mbstring
        - php-mcrypt
        - php-gd
        - php-xml
        - php
        - php-mysqlnd
        - php-fpm
        - php-common

    - name: set php.ini time zone
      lineinfile: "state=present dest=/etc/php.ini regexp=';date.timezone =' line='date.timezone = Asia/Taipei'"
    
    - name: set php.ini expose_php to off
      lineinfile: "state=present dest=/etc/php.ini regexp='expose_php = On' line='expose_php = Off'" 

    - name: set php.ini cgi.fix_pathinfo to off
      lineinfile: "dest=/etc/php.ini regexp=';cgi.fix_pathinfo=1' line='cgi.fix_pathinfo = 0'" 

    - name: setup nginx config
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
      - restart nginx
      - restart php-fpm
      
    - name: setup project virtual host
      template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/{{ PRJ_NAME }}.conf

      become: yes
      become_method: sudo
      
      