---
# add project ftp for CentOS 7

- name: add ftp logs directory
  file: path="/var/log/vsftpd" state=directory mode=0755
  
- name: create vsftpd log file
  file: path="/var/log/vsftpd/vsftpd.log" state=touch mode=0600
  
- name: create vsftpd xferlog
  file: path="/var/log/vsftpd/xferlog" state=touch mode=0600

- name: add FTP settings
  blockinfile:
    dest: /etc/vsftpd/vsftpd.conf
    block: |
      pasv_enable=YES
      pasv_min_port=65400
      pasv_max_port=65420
      chroot_local_user=YES
      anonymous_enable=NO
      local_root=/home
      xferlog_enable=YES
      xferlog_std_format=YES
      xferlog_file=/var/log/vsftpd/xferlog
      dual_log_enable=YES
      log_ftp_protocol=YES
      setproctitle_enable=YES

- name: FTP logrotate
  template: src=ftp-logrotate.j2 dest=/etc/logrotate.d/vsftpd
  notify:
  - restart ftp

