---
# tasks file for nginx
# for CentOS 7
   - name: create project user to login
     stat: path=/usr/bin/glances

   - name: add project user
     import_tasks: adduser.yml
     tags: add-user

   - name: For CentOS 7 series nginx installation
     import_tasks: c7web.yml
     when:
          - ansible_distribution_major_version == "7"
     
   - name: add nginx log rotate config
     template: src=logrotate.conf.j2 dest=/etc/logrotate.d/{{ PRJ_NAME }}
     
   - name: setup FTP config
     import_tasks: ftp.yml